/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionLaden;
    QAction *actionLaden_2;
    QWidget *centralwidget;
    QGroupBox *groupBox;
    QLabel *befehlTime_Label;
    QLabel *label_41;
    QLineEdit *quarzfrequenz_input;
    QLabel *label_42;
    QGroupBox *groupBox_2;
    QPushButton *reset_laufzeit_button;
    QLabel *laufzeit_Label;
    QLabel *label_43;
    QGroupBox *groupBox_4;
    QPushButton *reset_Button;
    QPushButton *ignore_button;
    QPushButton *go_button;
    QPushButton *next_button;
    QPushButton *debug_button;
    QPushButton *skip_button;
    QGroupBox *groupBox_5;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QPlainTextEdit *Console_Field;
    QTableWidget *dataSpeicher_table;
    QTableWidget *pin_table;
    QLabel *label_40;
    QLabel *gui_stackZeiger;
    QGroupBox *groupBox_3;
    QLabel *label_44;
    QLabel *gui_stack0;
    QGroupBox *groupBox_6;
    QLabel *label_45;
    QLabel *gui_stack4;
    QGroupBox *groupBox_7;
    QLabel *label_46;
    QLabel *gui_stack3;
    QGroupBox *groupBox_8;
    QLabel *label_48;
    QLabel *gui_stack2;
    QGroupBox *groupBox_9;
    QLabel *label_49;
    QLabel *gui_stack1;
    QGroupBox *groupBox_10;
    QLabel *label_50;
    QLabel *gui_stack5;
    QGroupBox *groupBox_11;
    QLabel *label_51;
    QLabel *gui_stack6;
    QGroupBox *groupBox_12;
    QLabel *label_52;
    QLabel *gui_stack7;
    QLabel *wdt_reset_label;
    QLabel *quarzfrequenz_Label;
    QLabel *pfad_label;
    QLabel *laeuft_label;
    QWidget *gridLayoutWidget_2;
    QGridLayout *gridLayout_2;
    QFrame *frame;
    QFrame *frame_2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *wReg_Label;
    QLabel *fsr_Label;
    QLabel *pcl_Label;
    QLabel *pcLath_Label;
    QLabel *status_Label;
    QFrame *frame_3;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QCheckBox *checkBox;
    QLabel *label_12;
    QLabel *pc_Label;
    QLabel *stackpointer_Label;
    QLabel *vt_Label;
    QLabel *wdt_Label;
    QLabel *label_39;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label;
    QFrame *frame_4;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *irp_Label;
    QLabel *rp1_Label;
    QLabel *rp0_Label;
    QLabel *t0_Label;
    QLabel *pd_Label;
    QLabel *z_Label;
    QLabel *dc_Label;
    QLabel *c_Label;
    QLabel *option_Label;
    QLabel *rbp_Label;
    QLabel *intedg_Label;
    QLabel *t0cs_Label;
    QLabel *t0se_Label;
    QLabel *psa_Label;
    QLabel *ps2_Label;
    QLabel *ps1_Label;
    QLabel *ps0_Label;
    QLabel *intcon_Label;
    QLabel *gie_Label;
    QLabel *pie_Label;
    QLabel *t0ie_Label;
    QLabel *inte_Label;
    QLabel *rbie_Label;
    QLabel *t0if_Label;
    QLabel *intf_Label;
    QLabel *rbif_Label;
    QLabel *label_47;
    QMenuBar *menubar;
    QMenu *menuDatei;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(1502, 838);
        MainWindow->setAutoFillBackground(true);
        actionLaden = new QAction(MainWindow);
        actionLaden->setObjectName("actionLaden");
        actionLaden_2 = new QAction(MainWindow);
        actionLaden_2->setObjectName("actionLaden_2");
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(1310, 320, 121, 81));
        befehlTime_Label = new QLabel(groupBox);
        befehlTime_Label->setObjectName("befehlTime_Label");
        befehlTime_Label->setGeometry(QRect(40, 60, 49, 16));
        label_41 = new QLabel(groupBox);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(90, 30, 49, 16));
        quarzfrequenz_input = new QLineEdit(groupBox);
        quarzfrequenz_input->setObjectName("quarzfrequenz_input");
        quarzfrequenz_input->setGeometry(QRect(10, 30, 61, 20));
        label_42 = new QLabel(groupBox);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(90, 60, 49, 16));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName("groupBox_2");
        groupBox_2->setGeometry(QRect(1310, 410, 120, 80));
        reset_laufzeit_button = new QPushButton(groupBox_2);
        reset_laufzeit_button->setObjectName("reset_laufzeit_button");
        reset_laufzeit_button->setGeometry(QRect(20, 50, 81, 24));
        laufzeit_Label = new QLabel(groupBox_2);
        laufzeit_Label->setObjectName("laufzeit_Label");
        laufzeit_Label->setGeometry(QRect(50, 20, 49, 16));
        label_43 = new QLabel(groupBox_2);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(90, 20, 49, 16));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName("groupBox_4");
        groupBox_4->setGeometry(QRect(1320, 500, 101, 221));
        reset_Button = new QPushButton(groupBox_4);
        reset_Button->setObjectName("reset_Button");
        reset_Button->setGeometry(QRect(10, 60, 80, 24));
        ignore_button = new QPushButton(groupBox_4);
        ignore_button->setObjectName("ignore_button");
        ignore_button->setGeometry(QRect(10, 90, 80, 24));
        go_button = new QPushButton(groupBox_4);
        go_button->setObjectName("go_button");
        go_button->setGeometry(QRect(10, 180, 80, 24));
        next_button = new QPushButton(groupBox_4);
        next_button->setObjectName("next_button");
        next_button->setGeometry(QRect(10, 120, 80, 24));
        debug_button = new QPushButton(groupBox_4);
        debug_button->setObjectName("debug_button");
        debug_button->setGeometry(QRect(10, 30, 80, 24));
        skip_button = new QPushButton(groupBox_4);
        skip_button->setObjectName("skip_button");
        skip_button->setGeometry(QRect(10, 150, 80, 24));
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName("groupBox_5");
        groupBox_5->setGeometry(QRect(560, 350, 731, 401));
        scrollArea = new QScrollArea(groupBox_5);
        scrollArea->setObjectName("scrollArea");
        scrollArea->setGeometry(QRect(0, 20, 771, 381));
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName("scrollAreaWidgetContents");
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 769, 379));
        Console_Field = new QPlainTextEdit(scrollAreaWidgetContents);
        Console_Field->setObjectName("Console_Field");
        Console_Field->setGeometry(QRect(0, 10, 721, 361));
        Console_Field->setFocusPolicy(Qt::WheelFocus);
        Console_Field->setTabStopDistance(4.000000000000000);
        Console_Field->setCursorWidth(10);
        scrollArea->setWidget(scrollAreaWidgetContents);
        dataSpeicher_table = new QTableWidget(centralwidget);
        if (dataSpeicher_table->columnCount() < 8)
            dataSpeicher_table->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        dataSpeicher_table->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        if (dataSpeicher_table->rowCount() < 30)
            dataSpeicher_table->setRowCount(30);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(0, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(1, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(2, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(3, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(4, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(5, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(6, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(7, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(8, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(9, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(10, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(11, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(12, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(13, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(14, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(15, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(16, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(17, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(18, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(19, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(20, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(21, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(22, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(23, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(24, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(25, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(26, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(27, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(28, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        dataSpeicher_table->setVerticalHeaderItem(29, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        __qtablewidgetitem38->setFlags(Qt::ItemIsEditable);
        dataSpeicher_table->setItem(0, 0, __qtablewidgetitem38);
        dataSpeicher_table->setObjectName("dataSpeicher_table");
        dataSpeicher_table->setGeometry(QRect(10, 10, 361, 561));
        dataSpeicher_table->horizontalHeader()->setMinimumSectionSize(10);
        dataSpeicher_table->horizontalHeader()->setDefaultSectionSize(39);
        dataSpeicher_table->verticalHeader()->setMinimumSectionSize(10);
        dataSpeicher_table->verticalHeader()->setDefaultSectionSize(24);
        pin_table = new QTableWidget(centralwidget);
        if (pin_table->columnCount() < 8)
            pin_table->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(0, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(1, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(2, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(3, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(4, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(5, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(6, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        pin_table->setHorizontalHeaderItem(7, __qtablewidgetitem46);
        if (pin_table->rowCount() < 6)
            pin_table->setRowCount(6);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        pin_table->setVerticalHeaderItem(0, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        pin_table->setVerticalHeaderItem(1, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        pin_table->setVerticalHeaderItem(2, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        pin_table->setVerticalHeaderItem(3, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        pin_table->setVerticalHeaderItem(4, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        pin_table->setVerticalHeaderItem(5, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        pin_table->setItem(0, 0, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        pin_table->setItem(0, 1, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        pin_table->setItem(0, 2, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        pin_table->setItem(0, 3, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        pin_table->setItem(0, 4, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        pin_table->setItem(0, 5, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        pin_table->setItem(0, 6, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        pin_table->setItem(0, 7, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        pin_table->setItem(1, 0, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        pin_table->setItem(1, 1, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        pin_table->setItem(1, 2, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        pin_table->setItem(1, 3, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        pin_table->setItem(1, 4, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        pin_table->setItem(1, 5, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        pin_table->setItem(1, 6, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        pin_table->setItem(1, 7, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        __qtablewidgetitem69->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 0, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        __qtablewidgetitem70->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 1, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        __qtablewidgetitem71->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 2, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        __qtablewidgetitem72->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 3, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        __qtablewidgetitem73->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 4, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        __qtablewidgetitem74->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 5, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        __qtablewidgetitem75->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 6, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        __qtablewidgetitem76->setCheckState(Qt::Unchecked);
        pin_table->setItem(2, 7, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        pin_table->setItem(3, 0, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        pin_table->setItem(3, 1, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        pin_table->setItem(3, 2, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        pin_table->setItem(3, 3, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        pin_table->setItem(3, 4, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        pin_table->setItem(3, 5, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        pin_table->setItem(3, 6, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        pin_table->setItem(3, 7, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        pin_table->setItem(4, 0, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        pin_table->setItem(4, 1, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        pin_table->setItem(4, 2, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        pin_table->setItem(4, 3, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        pin_table->setItem(4, 4, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        pin_table->setItem(4, 5, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        pin_table->setItem(4, 6, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        pin_table->setItem(4, 7, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        __qtablewidgetitem93->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 0, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        __qtablewidgetitem94->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 1, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        __qtablewidgetitem95->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 2, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        __qtablewidgetitem96->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 3, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        __qtablewidgetitem97->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 4, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        __qtablewidgetitem98->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 5, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        __qtablewidgetitem99->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 6, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        __qtablewidgetitem100->setCheckState(Qt::Unchecked);
        pin_table->setItem(5, 7, __qtablewidgetitem100);
        pin_table->setObjectName("pin_table");
        pin_table->setGeometry(QRect(390, 80, 601, 191));
        pin_table->setTabKeyNavigation(true);
        pin_table->horizontalHeader()->setVisible(false);
        pin_table->horizontalHeader()->setMinimumSectionSize(10);
        pin_table->horizontalHeader()->setDefaultSectionSize(70);
        pin_table->horizontalHeader()->setHighlightSections(true);
        pin_table->verticalHeader()->setVisible(true);
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(1150, 150, 81, 31));
        gui_stackZeiger = new QLabel(centralwidget);
        gui_stackZeiger->setObjectName("gui_stackZeiger");
        gui_stackZeiger->setGeometry(QRect(1180, 180, 21, 16));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName("groupBox_3");
        groupBox_3->setGeometry(QRect(1150, 10, 71, 51));
        label_44 = new QLabel(groupBox_3);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(10, 10, 49, 16));
        gui_stack0 = new QLabel(groupBox_3);
        gui_stack0->setObjectName("gui_stack0");
        gui_stack0->setGeometry(QRect(10, 30, 49, 16));
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName("groupBox_6");
        groupBox_6->setGeometry(QRect(1150, 280, 71, 51));
        label_45 = new QLabel(groupBox_6);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(10, 10, 49, 16));
        gui_stack4 = new QLabel(groupBox_6);
        gui_stack4->setObjectName("gui_stack4");
        gui_stack4->setGeometry(QRect(10, 30, 49, 16));
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName("groupBox_7");
        groupBox_7->setGeometry(QRect(1270, 240, 71, 51));
        label_46 = new QLabel(groupBox_7);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(10, 10, 49, 16));
        gui_stack3 = new QLabel(groupBox_7);
        gui_stack3->setObjectName("gui_stack3");
        gui_stack3->setGeometry(QRect(10, 30, 49, 16));
        groupBox_8 = new QGroupBox(centralwidget);
        groupBox_8->setObjectName("groupBox_8");
        groupBox_8->setGeometry(QRect(1300, 160, 71, 51));
        label_48 = new QLabel(groupBox_8);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(10, 10, 49, 16));
        gui_stack2 = new QLabel(groupBox_8);
        gui_stack2->setObjectName("gui_stack2");
        gui_stack2->setGeometry(QRect(10, 30, 49, 16));
        groupBox_9 = new QGroupBox(centralwidget);
        groupBox_9->setObjectName("groupBox_9");
        groupBox_9->setGeometry(QRect(1270, 70, 71, 51));
        label_49 = new QLabel(groupBox_9);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(10, 10, 49, 16));
        gui_stack1 = new QLabel(groupBox_9);
        gui_stack1->setObjectName("gui_stack1");
        gui_stack1->setGeometry(QRect(10, 30, 49, 16));
        groupBox_10 = new QGroupBox(centralwidget);
        groupBox_10->setObjectName("groupBox_10");
        groupBox_10->setGeometry(QRect(1040, 240, 71, 51));
        label_50 = new QLabel(groupBox_10);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(10, 10, 49, 16));
        gui_stack5 = new QLabel(groupBox_10);
        gui_stack5->setObjectName("gui_stack5");
        gui_stack5->setGeometry(QRect(10, 30, 49, 16));
        groupBox_11 = new QGroupBox(centralwidget);
        groupBox_11->setObjectName("groupBox_11");
        groupBox_11->setGeometry(QRect(1010, 160, 71, 51));
        label_51 = new QLabel(groupBox_11);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(10, 10, 49, 16));
        gui_stack6 = new QLabel(groupBox_11);
        gui_stack6->setObjectName("gui_stack6");
        gui_stack6->setGeometry(QRect(10, 30, 49, 16));
        groupBox_12 = new QGroupBox(centralwidget);
        groupBox_12->setObjectName("groupBox_12");
        groupBox_12->setGeometry(QRect(1040, 70, 71, 51));
        label_52 = new QLabel(groupBox_12);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(10, 10, 49, 16));
        gui_stack7 = new QLabel(groupBox_12);
        gui_stack7->setObjectName("gui_stack7");
        gui_stack7->setGeometry(QRect(10, 30, 49, 16));
        wdt_reset_label = new QLabel(centralwidget);
        wdt_reset_label->setObjectName("wdt_reset_label");
        wdt_reset_label->setGeometry(QRect(860, 315, 201, 41));
        wdt_reset_label->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 0);\n"
"font: 20pt \"Segoe UI\";"));
        wdt_reset_label->setFrameShape(QFrame::Box);
        quarzfrequenz_Label = new QLabel(centralwidget);
        quarzfrequenz_Label->setObjectName("quarzfrequenz_Label");
        quarzfrequenz_Label->setGeometry(QRect(1440, 350, 49, 16));
        pfad_label = new QLabel(centralwidget);
        pfad_label->setObjectName("pfad_label");
        pfad_label->setGeometry(QRect(0, 780, 801, 16));
        laeuft_label = new QLabel(centralwidget);
        laeuft_label->setObjectName("laeuft_label");
        laeuft_label->setGeometry(QRect(1330, 720, 81, 31));
        laeuft_label->setStyleSheet(QString::fromUtf8("color: red; font-size: 20px;"));
        gridLayoutWidget_2 = new QWidget(centralwidget);
        gridLayoutWidget_2->setObjectName("gridLayoutWidget_2");
        gridLayoutWidget_2->setGeometry(QRect(10, 590, 531, 161));
        gridLayout_2 = new QGridLayout(gridLayoutWidget_2);
        gridLayout_2->setObjectName("gridLayout_2");
        gridLayout_2->setContentsMargins(0, 0, 0, 0);
        frame = new QFrame(gridLayoutWidget_2);
        frame->setObjectName("frame");
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 30, 91, 121));
        frame_2->setStyleSheet(QString::fromUtf8("border: 1px solid black\n"
""));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        frame_2->setLineWidth(1);
        label_4 = new QLabel(frame_2);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(0, 10, 49, 16));
        label_4->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_5 = new QLabel(frame_2);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(0, 30, 49, 16));
        label_5->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_6 = new QLabel(frame_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(0, 50, 49, 16));
        label_6->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_7 = new QLabel(frame_2);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(0, 70, 49, 16));
        label_7->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_8 = new QLabel(frame_2);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(0, 90, 49, 16));
        label_8->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        wReg_Label = new QLabel(frame_2);
        wReg_Label->setObjectName("wReg_Label");
        wReg_Label->setGeometry(QRect(50, 10, 31, 16));
        fsr_Label = new QLabel(frame_2);
        fsr_Label->setObjectName("fsr_Label");
        fsr_Label->setGeometry(QRect(50, 30, 31, 16));
        pcl_Label = new QLabel(frame_2);
        pcl_Label->setObjectName("pcl_Label");
        pcl_Label->setGeometry(QRect(50, 50, 31, 16));
        pcLath_Label = new QLabel(frame_2);
        pcLath_Label->setObjectName("pcLath_Label");
        pcLath_Label->setGeometry(QRect(50, 70, 31, 16));
        status_Label = new QLabel(frame_2);
        status_Label->setObjectName("status_Label");
        status_Label->setGeometry(QRect(50, 90, 31, 16));
        frame_3 = new QFrame(frame);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(130, 30, 111, 121));
        frame_3->setStyleSheet(QString::fromUtf8("border: 1px solid black"));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_9 = new QLabel(frame_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(0, 10, 49, 16));
        label_9->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_10 = new QLabel(frame_3);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(0, 30, 71, 16));
        label_10->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_11 = new QLabel(frame_3);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(0, 50, 49, 16));
        label_11->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        checkBox = new QCheckBox(frame_3);
        checkBox->setObjectName("checkBox");
        checkBox->setGeometry(QRect(0, 70, 81, 22));
        checkBox->setStyleSheet(QString::fromUtf8("border 0pc"));
        checkBox->setChecked(true);
        label_12 = new QLabel(frame_3);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(0, 100, 49, 16));
        label_12->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        pc_Label = new QLabel(frame_3);
        pc_Label->setObjectName("pc_Label");
        pc_Label->setGeometry(QRect(70, 10, 31, 16));
        stackpointer_Label = new QLabel(frame_3);
        stackpointer_Label->setObjectName("stackpointer_Label");
        stackpointer_Label->setGeometry(QRect(70, 30, 31, 16));
        vt_Label = new QLabel(frame_3);
        vt_Label->setObjectName("vt_Label");
        vt_Label->setGeometry(QRect(70, 50, 31, 16));
        wdt_Label = new QLabel(frame_3);
        wdt_Label->setObjectName("wdt_Label");
        wdt_Label->setGeometry(QRect(30, 100, 71, 16));
        label_39 = new QLabel(frame_3);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(80, 100, 16, 16));
        label_39->setStyleSheet(QString::fromUtf8("border: 0px solid red"));
        label_2 = new QLabel(frame);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(130, 20, 61, 16));
        label_2->setStyleSheet(QString::fromUtf8("background: lightgrey"));
        label_3 = new QLabel(frame);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 0, 131, 16));
        label = new QLabel(frame);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 20, 49, 16));
        label->setStyleSheet(QString::fromUtf8("background: lightgrey"));
        frame_4 = new QFrame(frame);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(270, 10, 251, 141));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_13 = new QLabel(frame_4);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(0, 0, 21, 16));
        label_14 = new QLabel(frame_4);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(30, 0, 21, 16));
        label_15 = new QLabel(frame_4);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(60, 0, 21, 16));
        label_16 = new QLabel(frame_4);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(90, 0, 21, 16));
        label_17 = new QLabel(frame_4);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(120, 0, 21, 16));
        label_18 = new QLabel(frame_4);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(150, 0, 21, 16));
        label_19 = new QLabel(frame_4);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(170, 0, 21, 16));
        label_20 = new QLabel(frame_4);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(200, 0, 21, 16));
        label_21 = new QLabel(frame_4);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(0, 30, 49, 16));
        label_22 = new QLabel(frame_4);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(0, 60, 21, 16));
        label_23 = new QLabel(frame_4);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(30, 60, 41, 16));
        label_24 = new QLabel(frame_4);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(70, 60, 31, 16));
        label_25 = new QLabel(frame_4);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(100, 60, 31, 16));
        label_26 = new QLabel(frame_4);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(130, 60, 21, 16));
        label_27 = new QLabel(frame_4);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(160, 60, 21, 16));
        label_28 = new QLabel(frame_4);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(190, 60, 21, 16));
        label_29 = new QLabel(frame_4);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(220, 60, 21, 16));
        label_30 = new QLabel(frame_4);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(0, 90, 49, 16));
        label_31 = new QLabel(frame_4);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 110, 21, 16));
        label_32 = new QLabel(frame_4);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(30, 110, 21, 16));
        label_33 = new QLabel(frame_4);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(60, 110, 21, 16));
        label_34 = new QLabel(frame_4);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(90, 110, 31, 16));
        label_35 = new QLabel(frame_4);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(120, 110, 31, 16));
        label_36 = new QLabel(frame_4);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(150, 110, 21, 16));
        label_37 = new QLabel(frame_4);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(180, 110, 31, 16));
        label_38 = new QLabel(frame_4);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(210, 110, 31, 16));
        irp_Label = new QLabel(frame_4);
        irp_Label->setObjectName("irp_Label");
        irp_Label->setGeometry(QRect(0, 10, 31, 16));
        rp1_Label = new QLabel(frame_4);
        rp1_Label->setObjectName("rp1_Label");
        rp1_Label->setGeometry(QRect(30, 10, 31, 16));
        rp0_Label = new QLabel(frame_4);
        rp0_Label->setObjectName("rp0_Label");
        rp0_Label->setGeometry(QRect(60, 10, 31, 16));
        t0_Label = new QLabel(frame_4);
        t0_Label->setObjectName("t0_Label");
        t0_Label->setGeometry(QRect(90, 10, 31, 16));
        pd_Label = new QLabel(frame_4);
        pd_Label->setObjectName("pd_Label");
        pd_Label->setGeometry(QRect(120, 10, 31, 16));
        z_Label = new QLabel(frame_4);
        z_Label->setObjectName("z_Label");
        z_Label->setGeometry(QRect(150, 10, 31, 16));
        dc_Label = new QLabel(frame_4);
        dc_Label->setObjectName("dc_Label");
        dc_Label->setGeometry(QRect(170, 10, 31, 16));
        c_Label = new QLabel(frame_4);
        c_Label->setObjectName("c_Label");
        c_Label->setGeometry(QRect(200, 10, 31, 16));
        option_Label = new QLabel(frame_4);
        option_Label->setObjectName("option_Label");
        option_Label->setGeometry(QRect(50, 30, 31, 16));
        rbp_Label = new QLabel(frame_4);
        rbp_Label->setObjectName("rbp_Label");
        rbp_Label->setGeometry(QRect(0, 70, 31, 16));
        intedg_Label = new QLabel(frame_4);
        intedg_Label->setObjectName("intedg_Label");
        intedg_Label->setGeometry(QRect(30, 70, 31, 16));
        t0cs_Label = new QLabel(frame_4);
        t0cs_Label->setObjectName("t0cs_Label");
        t0cs_Label->setGeometry(QRect(70, 70, 31, 16));
        t0se_Label = new QLabel(frame_4);
        t0se_Label->setObjectName("t0se_Label");
        t0se_Label->setGeometry(QRect(100, 70, 31, 16));
        psa_Label = new QLabel(frame_4);
        psa_Label->setObjectName("psa_Label");
        psa_Label->setGeometry(QRect(130, 70, 31, 16));
        ps2_Label = new QLabel(frame_4);
        ps2_Label->setObjectName("ps2_Label");
        ps2_Label->setGeometry(QRect(160, 70, 31, 16));
        ps1_Label = new QLabel(frame_4);
        ps1_Label->setObjectName("ps1_Label");
        ps1_Label->setGeometry(QRect(190, 70, 31, 16));
        ps0_Label = new QLabel(frame_4);
        ps0_Label->setObjectName("ps0_Label");
        ps0_Label->setGeometry(QRect(220, 70, 31, 16));
        intcon_Label = new QLabel(frame_4);
        intcon_Label->setObjectName("intcon_Label");
        intcon_Label->setGeometry(QRect(50, 90, 31, 16));
        gie_Label = new QLabel(frame_4);
        gie_Label->setObjectName("gie_Label");
        gie_Label->setGeometry(QRect(0, 120, 31, 16));
        pie_Label = new QLabel(frame_4);
        pie_Label->setObjectName("pie_Label");
        pie_Label->setGeometry(QRect(30, 120, 31, 16));
        t0ie_Label = new QLabel(frame_4);
        t0ie_Label->setObjectName("t0ie_Label");
        t0ie_Label->setGeometry(QRect(60, 120, 31, 16));
        inte_Label = new QLabel(frame_4);
        inte_Label->setObjectName("inte_Label");
        inte_Label->setGeometry(QRect(90, 120, 31, 16));
        rbie_Label = new QLabel(frame_4);
        rbie_Label->setObjectName("rbie_Label");
        rbie_Label->setGeometry(QRect(120, 120, 31, 16));
        t0if_Label = new QLabel(frame_4);
        t0if_Label->setObjectName("t0if_Label");
        t0if_Label->setGeometry(QRect(150, 120, 31, 16));
        intf_Label = new QLabel(frame_4);
        intf_Label->setObjectName("intf_Label");
        intf_Label->setGeometry(QRect(180, 120, 31, 16));
        rbif_Label = new QLabel(frame_4);
        rbif_Label->setObjectName("rbif_Label");
        rbif_Label->setGeometry(QRect(210, 120, 31, 16));
        frame_2->raise();
        frame_3->raise();
        label_3->raise();
        label_2->raise();
        label->raise();
        frame_4->raise();

        gridLayout_2->addWidget(frame, 0, 0, 1, 1);

        label_47 = new QLabel(centralwidget);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(640, 270, 101, 21));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 1502, 22));
        menuDatei = new QMenu(menubar);
        menuDatei->setObjectName("menuDatei");
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuDatei->menuAction());
        menuDatei->addAction(actionLaden);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        actionLaden->setText(QCoreApplication::translate("MainWindow", "Laden", nullptr));
        actionLaden_2->setText(QCoreApplication::translate("MainWindow", "Laden", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindow", "Quarzfrequenz", nullptr));
        befehlTime_Label->setText(QCoreApplication::translate("MainWindow", "1.000", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Mhz", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "\302\265s", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("MainWindow", "Laufzeit", nullptr));
        reset_laufzeit_button->setText(QCoreApplication::translate("MainWindow", "Zur\303\274cksetzen", nullptr));
        laufzeit_Label->setText(QCoreApplication::translate("MainWindow", "0.0", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "\302\265s", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "Steuerpult", nullptr));
        reset_Button->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        ignore_button->setText(QCoreApplication::translate("MainWindow", "Ignore", nullptr));
        go_button->setText(QCoreApplication::translate("MainWindow", "Go ", nullptr));
        next_button->setText(QCoreApplication::translate("MainWindow", "Step/Next", nullptr));
        debug_button->setText(QCoreApplication::translate("MainWindow", "Debug", nullptr));
        skip_button->setText(QCoreApplication::translate("MainWindow", "Skip", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWindow", "Console Output", nullptr));
        Console_Field->setPlainText(QString());
        QTableWidgetItem *___qtablewidgetitem = dataSpeicher_table->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = dataSpeicher_table->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "01", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = dataSpeicher_table->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "02", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = dataSpeicher_table->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindow", "03", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = dataSpeicher_table->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindow", "04", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = dataSpeicher_table->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindow", "05", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = dataSpeicher_table->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindow", "06", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = dataSpeicher_table->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindow", "07", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = dataSpeicher_table->verticalHeaderItem(0);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = dataSpeicher_table->verticalHeaderItem(1);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindow", "08", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = dataSpeicher_table->verticalHeaderItem(2);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = dataSpeicher_table->verticalHeaderItem(3);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindow", "18", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = dataSpeicher_table->verticalHeaderItem(4);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("MainWindow", "20", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = dataSpeicher_table->verticalHeaderItem(5);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("MainWindow", "28", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = dataSpeicher_table->verticalHeaderItem(6);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("MainWindow", "30", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = dataSpeicher_table->verticalHeaderItem(7);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("MainWindow", "38", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = dataSpeicher_table->verticalHeaderItem(8);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("MainWindow", "40", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = dataSpeicher_table->verticalHeaderItem(9);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("MainWindow", "48", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = dataSpeicher_table->verticalHeaderItem(10);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("MainWindow", "50", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = dataSpeicher_table->verticalHeaderItem(11);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("MainWindow", "58", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = dataSpeicher_table->verticalHeaderItem(12);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("MainWindow", "60", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = dataSpeicher_table->verticalHeaderItem(13);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("MainWindow", "68", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = dataSpeicher_table->verticalHeaderItem(14);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("MainWindow", "70", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = dataSpeicher_table->verticalHeaderItem(15);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("MainWindow", "78", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = dataSpeicher_table->verticalHeaderItem(16);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("MainWindow", "80", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = dataSpeicher_table->verticalHeaderItem(17);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("MainWindow", "88", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = dataSpeicher_table->verticalHeaderItem(18);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("MainWindow", "90", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = dataSpeicher_table->verticalHeaderItem(19);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("MainWindow", "98", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = dataSpeicher_table->verticalHeaderItem(20);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("MainWindow", "A0", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = dataSpeicher_table->verticalHeaderItem(21);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("MainWindow", "A8", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = dataSpeicher_table->verticalHeaderItem(22);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("MainWindow", "B0", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = dataSpeicher_table->verticalHeaderItem(23);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("MainWindow", "C0", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = dataSpeicher_table->verticalHeaderItem(24);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("MainWindow", "C8", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = dataSpeicher_table->verticalHeaderItem(25);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("MainWindow", "D0", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = dataSpeicher_table->verticalHeaderItem(26);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = dataSpeicher_table->verticalHeaderItem(27);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("MainWindow", "E0", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = dataSpeicher_table->verticalHeaderItem(28);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("MainWindow", "E8", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = dataSpeicher_table->verticalHeaderItem(29);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("MainWindow", "F8", nullptr));

        const bool __sortingEnabled = dataSpeicher_table->isSortingEnabled();
        dataSpeicher_table->setSortingEnabled(false);
        dataSpeicher_table->setSortingEnabled(__sortingEnabled);

        QTableWidgetItem *___qtablewidgetitem38 = pin_table->verticalHeaderItem(0);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("MainWindow", "RA", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = pin_table->verticalHeaderItem(1);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("MainWindow", "TRIS", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = pin_table->verticalHeaderItem(2);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("MainWindow", "PIN", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = pin_table->verticalHeaderItem(3);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("MainWindow", "RB", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = pin_table->verticalHeaderItem(4);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("MainWindow", "TRIS", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = pin_table->verticalHeaderItem(5);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("MainWindow", "PIN", nullptr));

        const bool __sortingEnabled1 = pin_table->isSortingEnabled();
        pin_table->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem44 = pin_table->item(0, 0);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = pin_table->item(0, 1);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = pin_table->item(0, 2);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = pin_table->item(0, 3);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        QTableWidgetItem *___qtablewidgetitem48 = pin_table->item(0, 4);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = pin_table->item(0, 5);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = pin_table->item(0, 6);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = pin_table->item(0, 7);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = pin_table->item(1, 0);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = pin_table->item(1, 1);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = pin_table->item(1, 2);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = pin_table->item(1, 3);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem56 = pin_table->item(1, 4);
        ___qtablewidgetitem56->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem57 = pin_table->item(1, 5);
        ___qtablewidgetitem57->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem58 = pin_table->item(1, 6);
        ___qtablewidgetitem58->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem59 = pin_table->item(1, 7);
        ___qtablewidgetitem59->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem60 = pin_table->item(3, 0);
        ___qtablewidgetitem60->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        QTableWidgetItem *___qtablewidgetitem61 = pin_table->item(3, 1);
        ___qtablewidgetitem61->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        QTableWidgetItem *___qtablewidgetitem62 = pin_table->item(3, 2);
        ___qtablewidgetitem62->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        QTableWidgetItem *___qtablewidgetitem63 = pin_table->item(3, 3);
        ___qtablewidgetitem63->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        QTableWidgetItem *___qtablewidgetitem64 = pin_table->item(3, 4);
        ___qtablewidgetitem64->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        QTableWidgetItem *___qtablewidgetitem65 = pin_table->item(3, 5);
        ___qtablewidgetitem65->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        QTableWidgetItem *___qtablewidgetitem66 = pin_table->item(3, 6);
        ___qtablewidgetitem66->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        QTableWidgetItem *___qtablewidgetitem67 = pin_table->item(3, 7);
        ___qtablewidgetitem67->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem68 = pin_table->item(4, 0);
        ___qtablewidgetitem68->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem69 = pin_table->item(4, 1);
        ___qtablewidgetitem69->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem70 = pin_table->item(4, 2);
        ___qtablewidgetitem70->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem71 = pin_table->item(4, 3);
        ___qtablewidgetitem71->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem72 = pin_table->item(4, 4);
        ___qtablewidgetitem72->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem73 = pin_table->item(4, 5);
        ___qtablewidgetitem73->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem74 = pin_table->item(4, 6);
        ___qtablewidgetitem74->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        QTableWidgetItem *___qtablewidgetitem75 = pin_table->item(4, 7);
        ___qtablewidgetitem75->setText(QCoreApplication::translate("MainWindow", "i", nullptr));
        pin_table->setSortingEnabled(__sortingEnabled1);

        label_40->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Stackpointer</span></p></body></html>", nullptr));
        gui_stackZeiger->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>0</p></body></html>", nullptr));
        groupBox_3->setTitle(QString());
        label_44->setText(QCoreApplication::translate("MainWindow", "Adr. 0", nullptr));
        gui_stack0->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_6->setTitle(QString());
        label_45->setText(QCoreApplication::translate("MainWindow", "Adr. 4", nullptr));
        gui_stack4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_7->setTitle(QString());
        label_46->setText(QCoreApplication::translate("MainWindow", "Adr. 3", nullptr));
        gui_stack3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_8->setTitle(QString());
        label_48->setText(QCoreApplication::translate("MainWindow", "Adr. 2", nullptr));
        gui_stack2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_9->setTitle(QString());
        label_49->setText(QCoreApplication::translate("MainWindow", "Adr. 1", nullptr));
        gui_stack1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_10->setTitle(QString());
        label_50->setText(QCoreApplication::translate("MainWindow", "Adr. 5", nullptr));
        gui_stack5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_11->setTitle(QString());
        label_51->setText(QCoreApplication::translate("MainWindow", "Adr. 6", nullptr));
        gui_stack6->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_12->setTitle(QString());
        label_52->setText(QCoreApplication::translate("MainWindow", "Adr. 7", nullptr));
        gui_stack7->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        wdt_reset_label->setText(QString());
        quarzfrequenz_Label->setText(QCoreApplication::translate("MainWindow", "4,000000", nullptr));
        pfad_label->setText(QCoreApplication::translate("MainWindow", "PfadLabel", nullptr));
        laeuft_label->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "W-Reg", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "FSR", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "PCL", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "PCLATH", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Status", nullptr));
        wReg_Label->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        fsr_Label->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        pcl_Label->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        pcLath_Label->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        status_Label->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "PC", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Stackpointer", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "VT", nullptr));
        checkBox->setText(QCoreApplication::translate("MainWindow", "WDT aktiv", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "WDT", nullptr));
        pc_Label->setText(QCoreApplication::translate("MainWindow", "0000", nullptr));
        stackpointer_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        vt_Label->setText(QCoreApplication::translate("MainWindow", "FF", nullptr));
        wdt_Label->setText(QCoreApplication::translate("MainWindow", "0.0", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "\302\265s", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "unsichtbar", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Spezialfunktionsregister", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "sichtbar", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "IRP", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "RP1", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "RP0", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "TO", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "PD", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "DC", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "C", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Option", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "RBP", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "IntEdg", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "T0CS", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "T0SE", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "PSA", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "PS2", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "PS1", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "PS0", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "INTCON", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "GIE", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "PIE", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "T0IE", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "INTE", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "RBIE", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "T0IF", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "INTF", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "RBIF", nullptr));
        irp_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rp1_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rp0_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        t0_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pd_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        z_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        dc_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        c_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        option_Label->setText(QCoreApplication::translate("MainWindow", "FF", nullptr));
        rbp_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        intedg_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        t0cs_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        t0se_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        psa_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        ps2_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        ps1_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        ps0_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        intcon_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        gie_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pie_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        t0ie_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        inte_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rbie_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        t0if_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        intf_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rbif_Label->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "Pins checked =1", nullptr));
        menuDatei->setTitle(QCoreApplication::translate("MainWindow", "Datei", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
